In [1]:
###Deliverable 3. Create a Travel Itinerary Map

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Jawad,IN,63.86,clear sky,24.60,74.85,हर मंदिर जावद
1,1,Mahebourg,MU,77.00,shower rain,-20.41,57.70,Shandrani Beachcomber Resort & Spa
2,2,Busselton,AU,55.99,few clouds,-33.65,115.33,Observatory Guest House
3,3,Avarua,CK,73.40,broken clouds,-21.21,-159.78,Paradise Inn
4,4,Alofi,NU,75.20,overcast clouds,-19.06,-169.92,Taloa Heights

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
vacation_destination_pick = vacation_df.loc[(vacation_df['Max Temp'] >= 50)&(vacation_df['Max Temp'] <= 56)]
vacation_destination_pick

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,2,Busselton,AU,55.99,few clouds,-33.65,115.33,Observatory Guest House
28,39,Punta Arenas,CL,51.80,broken clouds,-53.15,-70.92,Hotel Dreams Del Estrecho
51,80,Bridlington,GB,50.00,light rain,54.08,-0.19,Expanse Bridlington Seafront Hotel
57,89,Hasaki,JP,51.80,broken clouds,35.73,140.83,Inubosaki Kanko Hotel
76,130,Codrington,AU,52.02,scattered clouds,-38.27,141.97,Codrington Gardens Bed And Breakfast
77,131,Brigantine,US,50.00,clear sky,39.41,-74.36,Legacy Vacation Resort Brigantine Beach
91,151,Mount Gambier,AU,51.80,clear sky,-37.83,140.77,Commodore on the Park
124,213,Huilong,CN,53.01,light rain,31.81,121.66,Hilton Garden Inn Qidong
136,240,Bathurst,AU,53.01,few clouds,-33.42,149.58,Bathurst Motor Inn
139,244,Dunedin,NZ,51.01,clear sky,-45.87,170.50,Scenic Hotel Southern Cross
149,264,Shingu,JP,52.09,clear sky,33.73,135.98,Shingu UI Hotel
175,305,Yarim,YE,54.25,overcast clouds,14.30,44.38,جامع القحيزة
180,311,Havelock,US,55.00,clear sky,34.88,-76.90,Sherwood Motel
187,324,Sabha,LY,55.65,few clouds,27.04,14.43,محطة ام الارانب -سبها مواصلات
197,343,Oyama,JP,54.00,light rain,36.30,139.80,Toyoko Inn Oyama-eki Higashi-guchi No.1
201,348,Margate,GB,50.00,overcast clouds,51.38,1.39,Premier Inn Margate hotel
202,352,Blyth,GB,51.80,overcast clouds,55.13,-1.51,Luxury Caravan with Sea Views close to Beach
207,366,Lexington,US,50.00,few clouds,37.99,-84.48,DoubleTree Suites by Hilton Hotel Lexington
212,374,Elizabeth City,US,52.00,clear sky,36.29,-76.25,Hampton Inn Elizabeth City
213,376,Le Pradet,FR,55.40,clear sky,43.11,6.02,Hôtel Kyriad Toulon La Garde
224,394,Lannion,FR,55.40,overcast clouds,48.75,-3.42,Hotel Arcadia
227,401,Half Moon Bay,US,53.01,overcast clouds,37.46,-122.43,"The Ritz-Carlton, Half Moon Bay"
238,424,Coihaique,CL,53.60,broken clouds,-45.58,-72.07,Diego De Almagro Coyhaique
243,430,Mehriz,IR,50.00,few clouds,31.59,54.43,Mehrgard dwelling/سرای مهرگرد
246,434,Cortes,ES,50.00,overcast clouds,41.94,-1.44,Rincon de bu
252,448,Bereda,ES,55.99,broken clouds,43.27,-7.54,Pazo de Verdes
260,464,Silver City,US,50.00,scattered clouds,32.77,-108.28,Copper Manor Motel
264,469,Torbay,CA,53.01,heavy intensity rain,47.67,-52.73,Gallows Cove
270,476,Rio Linda,US,50.00,clear sky,38.69,-121.45,Lees bed and breakfast
271,478,Constantine,DZ,55.40,scattered clouds,36.37,6.61,Grand Hotel Cirta
273,480,Reading,GB,51.01,clear sky,51.46,-0.97,The Roseate Reading
282,494,Atherton,GB,53.01,overcast clouds,53.52,-2.49,The Mercury Motel
290,511,Kaita,JP,50.00,scattered clouds,34.37,132.55,Hiroshima Hotel / La Michel Funakoshi
293,519,Las Vegas,US,55.99,clear sky,36.17,-115.14,Plaza Hotel & Casino
297,530,Ukiah,US,50.00,clear sky,39.15,-123.21,Hampton Inn Ukiah
309,560,Greenwood,US,53.01,clear sky,34.17,-82.12,Quality Inn Greenwood Hwy 25
333,601,Nagato,JP,53.60,few clouds,34.38,131.20,いそう庵
344,631,Worthing,GB,52.00,few clouds,50.81,-0.37,The Chatsworth Hotel
350,638,Hutchinson,US,55.00,mist,38.06,-97.93,Hampton Inn Hutchinson
367,670,Southampton,GB,51.80,clear sky,50.90,-1.40,Leonardo Royal Southampton Grand Harbour
371,678,Xunchang,CN,51.22,overcast clouds,28.45,104.72,Jiabin Inn
372,679,Tumut,AU,55.06,few clouds,-35.30,148.22,Amaroo Motel
374,681,Vila,PT,53.01,light rain,42.03,-8.16,Hotel Castrum Villae
376,683,Tateyama,JP,51.01,light rain,34.98,139.87,Tateyama Seaside Hotel

In [24]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Brigantine']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Brigantine']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Lexington']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Elizabeth City'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Silver City']

In [25]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start.to_numpy()[0][5], vacation_start.to_numpy()[0][6])
end = (vacation_end.to_numpy()[0][5], vacation_end.to_numpy()[0][6])
stop1 = (vacation_stop1.to_numpy()[0][5], vacation_stop1.to_numpy()[0][6])
stop2 = (vacation_stop2.to_numpy()[0][5], vacation_stop2.to_numpy()[0][6])
stop3 =(vacation_stop3.to_numpy()[0][5], vacation_stop3.to_numpy()[0][6])

In [26]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
vacation_directions = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')
fig.add_layer(vacation_directions)
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,131,Brigantine,US,50.0,clear sky,39.41,-74.36,Legacy Vacation Resort Brigantine Beach
1,366,Lexington,US,50.0,few clouds,37.99,-84.48,DoubleTree Suites by Hilton Hotel Lexington
2,374,Elizabeth City,US,52.0,clear sky,36.29,-76.25,Hampton Inn Elizabeth City
3,464,Silver City,US,50.0,scattered clouds,32.77,-108.28,Copper Manor Motel

In [28]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [29]:
# 11a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))