In [10]:
###Deliverable 1: Retrieve Weather Data

In [2]:
import random
import pandas as pd
import numpy as np
import requests
from config import weather_api_key
from citipy import citipy

In [3]:
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)

In [4]:
coordinates = list(lat_lngs)
cities = []

In [5]:
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    if city in cities: continue
    cities.append(city)
len(cities)

750

In [6]:
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [7]:
weather_data = []

for city in cities:
    city_url = url + "&q=" + city.replace(" ","+")
    
    try:
        city_weather = requests.get(city_url).json()
        city_country = city_weather['sys']['country']
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_description = city_weather["weather"][0]["description"]
        weather_data.append({"City": city.title(),
                          "Country": city_country,
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Current Description": city_description})


    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")

print("Data Retrieval Complete      ")
print("-----------------------------")

City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
-----------------------------
Data Retrieval Complete
-----------------------------

In [8]:
weather_data_df = pd.DataFrame(weather_data)
weather_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Jawad,IN,24.60,74.85,63.86,32,0,4.63,clear sky
1,Mahebourg,MU,-20.41,57.70,77.00,78,40,11.41,shower rain
2,Busselton,AU,-33.65,115.33,55.99,88,23,1.99,few clouds
3,Avarua,CK,-21.21,-159.78,73.40,88,66,1.12,broken clouds
4,Alofi,NU,-19.06,-169.92,75.20,94,90,6.93,overcast clouds
...,...,...,...,...,...,...,...,...,...
686,Washington,US,47.50,-120.50,37.00,90,100,2.37,overcast clouds
687,Torres,BR,-29.34,-49.73,78.33,65,0,18.66,clear sky
688,Mercedes,AR,-34.65,-59.43,91.99,42,98,1.01,overcast clouds
689,Bialong,PH,6.98,124.89,75.45,88,79,1.68,broken clouds
690,Formosa,AR,-26.18,-58.18,98.60,23,0,17.22,clear sky

In [9]:
output_data_file = "WeatherPy_Database.csv"
weather_data_df.to_csv(output_data_file, index_label="Weather_ID")